// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClCcx35TUZRatVC4TeApeJ5-x24e3a2ec',
    appId: '1:821173608627:web:5cc6598ec553d33299d0c6',
    messagingSenderId: '821173608627',
    projectId: 'stock-sync-app',
    authDomain: 'stock-sync-app.firebaseapp.com',
    storageBucket: 'stock-sync-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGgcsnulGbGEziwX_xH2rTwKjM06vDEI',
    appId: '1:431718014309:android:3b038f4dd8034e87e1558c',
    messagingSenderId: '431718014309',
    projectId: 'stock-sync-b5604',
    storageBucket: 'stock-sync-b5604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBowLuDQcfOMXMUO-_X708MzjFoVOujXao',
    appId: '1:431718014309:ios:c06ce7e8049165a2e1558c',
    messagingSenderId: '431718014309',
    projectId: 'stock-sync-b5604',
    storageBucket: 'stock-sync-b5604.appspot.com',
    iosBundleId: 'com.example.stockSync',
  );

}